### ISSUE TITLE
Neel And CrossBrowdy Support?

### ISSUE THREAD

**Issue by topcheese** [juancarlospaco/grabulma#1]
Hi, I just started checking out these projects, but I'm thinking they might make a killer Nim project if put together.  I thought I'd get your thoughts on it.  It would be nice to be able to design and build modules for CrossBrowdy, using GraBulma and Nim.  Then use Neel to ship clients?
~Thanks!
https://github.com/Niminem/Neel
https://crossbrowdy.com

**Comment by juancarlospaco** [comment]
[I made my own Electron replacement.](https://juancarlospaco.github.io/webgui)
[I also made a clon for Spectre thats more powerful than Bulma.](https://juancarlospaco.github.io/grapespectre)
I do not understand what is CrossBrowdy, I've read the web but still I do not understand it.
I do not use NPM stuff because I do everything with Karax.
I am not sure I understand your idea whatever that is.

**Comment by topcheese** [comment]
Well that's embarrasing, I should've known you made WebGUI.  It does look nice, and I'm not sure why I didn't think of it.  I was only thinking of spreading the love.  I also forgot to check out Spectre again, and so I just went with Bulma.
I just ran across CB yesterday.  It appears to be a JavaScript framework that has some nice features.  It's also a new project, and again I like to show some love back to developers that give it to me.
I also don't like to do NPM, so that's great news to me. Concerning CB, it uses JS modules, and I thought it would be great to be able to create them with GB.
https://crossbrowdy.com/basic_tutorial/general/modules

Anyway it was something I was just looking into doing, since I haven't decided on a GUI project to use with Nim Yet.  I like NimX, but projects like your webGui and Neel look better.
Thanks for your response!

**Comment by topcheese** [comment]
Well actually I don't like the looks of GTK and Webkit.  The prospect of being able to use a web GUI is what looks to be a better option.  I guess I'll have to play around with it and get back to you if I'm able to come up with something.

**Comment by juancarlospaco** [comment]
I think it depends on what you want to do, and personal taste. :shrug: 
I like nimqml and webgui.

**Comment by topcheese** [comment]
I see I should have talked to you first.  I like the Spectre integration.  I'lll have to look more into webgui.  I'm guessing you feel it's a better option than chrome.

**Comment by juancarlospaco** [comment]
You can use Karax and Spectre with webgui too.

**Comment by topcheese** [comment]
And come to find out I didn't have to install any dependencies on my Mac for webgui.  I guess I can do webkit after all.  I'll close this out, because I'll be looking at grapespectre, webgui, and CrossBrowdy.
I've also been reading up on GrapesJS.  I may just fork your project once I get up to speed on things.
~Thanks again!
